name: 'Code Pipeline Deployment List'
description: 'Run a mainframe generate using Code Pipeline.'
branding:
  icon: play
  color: orange
inputs:
  ces_url:
    description: 'The URL to send requests to.'
    required: true
  ces_token:
    description: 'The token to use when connecting to Code Pipeline through CES.'
    required: true
  srid:
    description: 'The ID for the instance of Code Pipeline to connect to'
    required: true
  runtime_configuration:
    description: 'The runtime configuration used when connecting to Code Pipeline'
    required: false
  assignment_id:
    description: 'The container for which you intend to generate tasks.'
    required: false
  level:
    description: 'The level that the tasks exist at in the assignment'
    required: false
  task_id:
    description: 'The comma-separated list of task IDs for the tasks that need to be generated'
    required: false
  generate_automatically:
    description: 'The request parameters for the generate will come from JSON passed in this input. This option is only valid when used in combination with a Git to Code Pipeline Integration step'
    required: false
  change_type: 
    description: 'S for standard, I for incidental, or E for emergency. Default value of S'
    required: false
    default: 'S'
  execution_status:
    description: 'I for immediate execution or at start date/time, H to create request in hold'
    required: false
    default: 'I'
  auto_deploy:
    description: 'Generates can be set up to automatically Deploy as well by an option set up by the Code Pipeline. The default is to not use Auto Deploy. If the Auto Deploy option is set-up through Code Pipeline, then you may use this option to automatically deploy instead of using the deployAutomatically option within the DeployTask/DeployAssignment/DeployRelease actions'
    required: true
    default: 'false'
outputs:
  generate_failed_count:
    description: 'The number of tasks that failed to generate'
  generate_success_count:
    description: 'The number of tasks that generated successfully'
  has_failures:
    description: 'Whether there were any generate failures'
  is_timed_out:
    description: 'Whether the generate timed out'
  task_count:
    description: 'The total number of tasks a generate was initiated against'
  set_id:
    description: 'The ID of the set that was used for processing'
  url:
    description: 'The URL that can be used to retrieve information about the set that was used for processing'
  output_json:
    description: 'the JSON output from build'
runs:
  using: 'node12'
  main: 'dist/index.js'
